# First-stage vendor_ramdisk kernel modules for OrangeFox recovery.
#
# Loaded by first-stage init in ramdisk00, the same place and order the
# working LineageOS vendor_boot uses. This is early enough for the MTK
# watchdog/hang-detect modules (mtk_wdt, aee_hangdet, monitor_hang).
# Loading them late via TWRP left the watchdog unkicked and reset the
# device at ~9s with no pstore.

BOARD_VENDOR_RAMDISK_KERNEL_MODULES := \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/8250_mtk.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/adapter_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/adsp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/aee_aed.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/aee_hangdet.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/aee_rs.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/arm_dsu_pmu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/blocktag.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/bootprof.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/bus-parity.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/cache-parity.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/charger_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-bringup.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-chk-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-dbg-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-disable-unused.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-fmeter-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-adsp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-bus.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-cam.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-ccu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-img.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-mdpsys.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-mmsys.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-peri.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-vcodec.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-vlp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clkbuf.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/cmdq-platform-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/cmdq_helper_inf.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/cqhci.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/dbg_error_flag.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/dbgtop-drm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/device-apc-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/device-apc-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/drm_display_helper.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/drm_dma_helper.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/emi-mpu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/emi-slb.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/emi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/extcon-mtk-usb.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/extdev_io_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/ffa-module.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/fsa4480-i2c.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/gf_tee.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/hall.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/hardware_info.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/hx9031as.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/hx9036.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/i2c-mt65xx.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/industrialio-triggered-buffer.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/iommu_debug.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/iommu_secure.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/irq-dbg.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/isee-ffa.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/kfifo_buf.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/last_bus.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/leds-mtk-disp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/leds-mtk-pwm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/leds-mtk.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/lenovo_charge_sysfs.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/log_store.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mcDrvModule-ffa.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mcupm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mdp_drv_mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mediatek-cpufreq-hw.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mediatek-drm-gateic.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mediatek-drm-panel-drv.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mediatek-drm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mkp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mm8013a_gauge.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mmprofile.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mmqos-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mmqos-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/monitor_hang.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mrdump.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6315-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6338-core.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6363-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6368-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6375-adc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6375-auxadc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6375-battery.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6375-charger.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6375.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6685-audclk.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6685-core.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6897_dcm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-afe-external.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-cmdq-drv-ext.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-dvfsrc-devfreq.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-dvfsrc-helper.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-dvfsrc-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-dvfsrc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-emi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-icc-core.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-kpd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mbox-mailbox.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mbox.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmc-dbg.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmdvfs-debug.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmdvfs-ftrace.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmdvfs-v3-start.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmdvfs-v3.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmdvfs.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mminfra-debug.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mminfra-imax.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mml-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mml.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-pm-domain-disable-unused.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-pmic-keys.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-pmic-wrap.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-scpsys-bringup.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-scpsys-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-scpsys.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-smi-dbg.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-smi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-socinfo.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-spmi-pmic-adc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-spmi-pmic.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-swpm-perf-arm-pmu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-uart-apdma.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-vmm-spm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_battery_oc_throttling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_charger_algorithm_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_charger_framework.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_chg_type_det.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_dcm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_disp_notify.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_dramc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_dynamic_loading_throttling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_iommu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_low_battery_throttling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_mdpm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_panel_ext.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pbm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pd_adapter.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pd_charging.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pep.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pep20.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pep40.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pep45.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pep50.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_printk_ctrl.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_rpmsg_mbox.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_slbc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_sync.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_tinysys_ipi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_wdt.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtu3.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mux_switch.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/nt36532.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/nu2115_chargepump.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/nvmem_mtk-devinfo.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-alpha-jdi-nt36672e-cphy-vdo.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-alpha-jdi-nt36672e-vdo-120hz-hfp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-alpha-jdi-nt36672e-vdo-120hz.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-alpha-jdi-nt36672e-vdo-60hz.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-nt36532-dsi-vdo-boe.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-nt36532-dsi-vdo-tianma-paper.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-nt36532-dsi-vdo-tianma.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-nt37801-cmd-fhd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-samsung-ana6705-cmd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-truly-nt35595-cmd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-truly-td4330-cmd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pd-chk-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pd_dbg_info.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/phy-mtk-ufs.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/phy-mtk-xsphy.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pidmap.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pinctrl-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pinctrl-mtk-common-v2_debug.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pinctrl-mtk-v2.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pmic_lbat_service.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pmic_lvsys_notify.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/ps5170.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pwm-mtk-disp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/reboot-mode.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/regulator-vibrator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/reset-ti-syscon.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rpmb-mtk.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rpmb.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rt4831a_drv.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rt5133-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rt6160-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rt_pd_manager.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rtc-mt6685.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sec-rng.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sec.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sensors_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sgm37604a.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sgm37604a_second.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/slbc_ipi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/slbc_mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/slbc_trace.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sm5109.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/smpu-hook-v1.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/smpu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/spi-mt65xx.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/spmi-mtk-mpu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/spmi-mtk-pmif.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/syscon-reboot-mode.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/system_heap.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/tcpc_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/tcpc_mt6375.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/tcpci_late_sync.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/teeperf.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/timer-mediatek.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/tinysys-scmi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/tui-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/uarthub_drv.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/ufs-mediatek-dbg.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/ufs-mediatek-mod.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/upm6720_chargepump.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/usb_boost.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/usb_dp_selector.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/usb_meta.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/vcp_status.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/xhci-mtk-hcd-v2.ko \

BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := \
    bootprof.ko \
    mrdump.ko \
    aee_aed.ko \
    aee_hangdet.ko \
    monitor_hang.ko \
    mkp.ko \
    dbgtop-drm.ko \
    irq-dbg.ko \
    cache-parity.ko \
    mtk_sync.ko \
    mtk_disp_notify.ko \
    mtk_printk_ctrl.ko \
    log_store.ko \
    nvmem_mtk-devinfo.ko \
    mtk_wdt.ko \
    timer-mediatek.ko \
    sec-rng.ko \
    device-apc-common.ko \
    device-apc-mt6897.ko \
    pinctrl-mtk-v2.ko \
    pinctrl-mt6897.ko \
    clk-common.ko \
    clk-mt6897.ko \
    clk-mt6897-adsp.ko \
    clk-mt6897-cam.ko \
    clk-mt6897-img.ko \
    clk-mt6897-mmsys.ko \
    clk-mt6897-peri.ko \
    clk-mt6897-bus.ko \
    clk-mt6897-mdpsys.ko \
    clk-mt6897-vlp.ko \
    clk-mt6897-vcodec.ko \
    clk-mt6897-ccu.ko \
    mtk-pmic-wrap.ko \
    mtk-spmi-pmic.ko \
    spmi-mtk-pmif.ko \
    mt6315-regulator.ko \
    mt6363-regulator.ko \
    mt6368-regulator.ko \
    mtk-vmm-spm.ko \
    mtk-scpsys.ko \
    mtk-scpsys-mt6897.ko \
    mtk-scpsys-bringup.ko \
    mt6897_dcm.ko \
    mtk_dcm.ko \
    mtk-dvfsrc.ko \
    mtk-dvfsrc-regulator.ko \
    mtk-dvfsrc-devfreq.ko \
    clk-bringup.ko \
    clk-chk-mt6897.ko \
    pd-chk-mt6897.ko \
    clk-fmeter-mt6897.ko \
    mtk-emi.ko \
    mtk-dvfsrc-helper.ko \
    mtk_dramc.ko \
    mtk-smi.ko \
    mtk-smi-dbg.ko \
    mtk-icc-core.ko \
    mtk-mmdvfs-ftrace.ko \
    mtk-mmdvfs-v3.ko \
    mtk-mmdvfs.ko \
    mtk-mmdvfs-debug.ko \
    mmqos-common.ko \
    mmqos-mt6897.ko \
    iommu_debug.ko \
    iommu_secure.ko \
    mtk_iommu.ko \
    system_heap.ko \
    mtk-mminfra-debug.ko \
    mtk-mminfra-imax.ko \
    mtk-cmdq-drv-ext.ko \
    cmdq-platform-mt6897.ko \
    cmdq_helper_inf.ko \
    mdp_drv_mt6897.ko \
    mtk-mml.ko \
    mtk-mml-mt6897.ko \
    drm_dma_helper.ko \
    mtk_panel_ext.ko \
    panel-alpha-jdi-nt36672e-vdo-60hz.ko \
    panel-nt36532-dsi-vdo-boe.ko \
    panel-nt36532-dsi-vdo-tianma.ko \
    panel-nt36532-dsi-vdo-tianma-paper.ko \
    panel-alpha-jdi-nt36672e-vdo-120hz.ko \
    panel-alpha-jdi-nt36672e-cphy-vdo.ko \
    panel-alpha-jdi-nt36672e-vdo-120hz-hfp.ko \
    panel-truly-td4330-cmd.ko \
    panel-truly-nt35595-cmd.ko \
    panel-nt37801-cmd-fhd.ko \
    panel-samsung-ana6705-cmd.ko \
    mtk-afe-external.ko \
    mediatek-drm-gateic.ko \
    mediatek-drm-panel-drv.ko \
    drm_display_helper.ko \
    mediatek-drm.ko \
    aee_rs.ko \
    rt4831a_drv.ko \
    sm5109.ko \
    sgm37604a.ko \
    sgm37604a_second.ko \
    mmprofile.ko \
    mtk-uart-apdma.ko \
    uarthub_drv.ko \
    8250_mtk.ko \
    phy-mtk-xsphy.ko \
    xhci-mtk-hcd-v2.ko \
    mtu3.ko \
    usb_boost.ko \
    mux_switch.ko \
    ps5170.ko \
    usb_dp_selector.ko \
    mt6685-core.ko \
    mt6685-audclk.ko \
    mt6338-core.ko \
    clkbuf.ko \
    ffa-module.ko \
    teeperf.ko \
    mcDrvModule-ffa.ko \
    isee-ffa.ko \
    mtk-spmi-pmic-adc.ko \
    pinctrl-mtk-common-v2_debug.ko \
    cqhci.ko \
    mtk-mmc-dbg.ko \
    mtk-mmc.ko \
    phy-mtk-ufs.ko \
    rpmb.ko \
    rpmb-mtk.ko \
    ufs-mediatek-mod.ko \
    ufs-mediatek-dbg.ko \
    blocktag.ko \
    pidmap.ko \
    mtk-pmic-keys.ko \
    mtk-kpd.ko \
    tui-common.ko \
    regulator-vibrator.ko \
    i2c-mt65xx.ko \
    mtk_dramc.ko \
    spi-mt65xx.ko \
    mt6375.ko \
    nt36532.ko \
    extdev_io_class.ko \
    rt5133-regulator.ko \
    rt6160-regulator.ko \
    rtc-mt6685.ko \
    industrialio-triggered-buffer.ko \
    kfifo_buf.ko \
    mt6375-adc.ko \
    mt6375-auxadc.ko \
    adapter_class.ko \
    charger_class.ko \
    mtk_charger_algorithm_class.ko \
    mt6375-charger.ko \
    pd_dbg_info.ko \
    tcpc_class.ko \
    tcpc_mt6375.ko \
    mtk_pd_adapter.ko \
    mt6375-battery.ko \
    mtk_charger_framework.ko \
    mtk_chg_type_det.ko \
    mtk_pep40.ko \
    mtk_pep45.ko \
    mtk_pep50.ko \
    mtk_pd_charging.ko \
    mtk_pep20.ko \
    mtk_pep.ko \
    rt_pd_manager.ko \
    fsa4480-i2c.ko \
    pwm-mtk-disp.ko \
    leds-mtk.ko \
    leds-mtk-disp.ko \
    leds-mtk-pwm.ko \
    extcon-mtk-usb.ko \
    tcpci_late_sync.ko \
    mtk-mbox-mailbox.ko \
    tinysys-scmi.ko \
    arm_dsu_pmu.ko \
    mtk-swpm-perf-arm-pmu.ko \
    pmic_lbat_service.ko \
    pmic_lvsys_notify.ko \
    reset-ti-syscon.ko \
    reboot-mode.ko \
    syscon-reboot-mode.ko \
    adsp.ko \
    mtk_slbc.ko \
    slbc_mt6897.ko \
    slbc_ipi.ko \
    slbc_trace.ko \
    mediatek-cpufreq-hw.ko \
    vcp_status.ko \
    emi.ko \
    emi-mpu.ko \
    smpu.ko \
    smpu-hook-v1.ko \
    emi-slb.ko \
    mtk-socinfo.ko \
    mm8013a_gauge.ko \
    upm6720_chargepump.ko \
    nu2115_chargepump.ko \
    lenovo_charge_sysfs.ko \
    hx9031as.ko \
    hx9036.ko \
    sensors_class.ko \
    hall.ko \
    usb_meta.ko \
    dbg_error_flag.ko \
    bus-parity.ko \
    last_bus.ko \
    hardware_info.ko \

