# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#
# Moto Pad 60 Pro (XT2571-1) kernel module manifest.
# Counts: vr=222 vd=205 sd=60

# vendor_ramdisk modules (alphabetical)
BOARD_VENDOR_RAMDISK_KERNEL_MODULES := \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/8250_mtk.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/adapter_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/adsp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/aee_aed.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/aee_hangdet.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/aee_rs.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/arm_dsu_pmu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/blocktag.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/bootprof.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/bus-parity.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/cache-parity.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/charger_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-bringup.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-chk-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-dbg-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-disable-unused.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-fmeter-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-adsp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-bus.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-cam.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-ccu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-img.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-mdpsys.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-mmsys.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-peri.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-vcodec.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897-vlp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clk-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/clkbuf.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/cmdq-platform-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/cmdq_helper_inf.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/cqhci.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/dbg_error_flag.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/dbgtop-drm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/device-apc-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/device-apc-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/drm_display_helper.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/drm_dma_helper.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/emi-mpu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/emi-slb.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/emi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/extcon-mtk-usb.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/extdev_io_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/ffa-module.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/fsa4480-i2c.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/gf_tee.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/hall.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/hardware_info.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/hx9031as.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/hx9036.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/i2c-mt65xx.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/industrialio-triggered-buffer.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/iommu_debug.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/iommu_secure.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/irq-dbg.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/isee-ffa.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/kfifo_buf.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/last_bus.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/leds-mtk-disp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/leds-mtk-pwm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/leds-mtk.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/lenovo_charge_sysfs.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/log_store.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mcDrvModule-ffa.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mcupm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mdp_drv_mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mediatek-cpufreq-hw.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mediatek-drm-gateic.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mediatek-drm-panel-drv.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mediatek-drm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mkp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mm8013a_gauge.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mmprofile.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mmqos-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mmqos-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/monitor_hang.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mrdump.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6315-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6338-core.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6363-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6368-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6375-adc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6375-auxadc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6375-battery.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6375-charger.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6375.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6685-audclk.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6685-core.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mt6897_dcm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-afe-external.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-cmdq-drv-ext.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-dvfsrc-devfreq.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-dvfsrc-helper.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-dvfsrc-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-dvfsrc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-emi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-icc-core.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-kpd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mbox-mailbox.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mbox.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmc-dbg.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmdvfs-debug.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmdvfs-ftrace.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmdvfs-v3-start.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmdvfs-v3.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mmdvfs.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mminfra-debug.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mminfra-imax.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mml-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-mml.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-pm-domain-disable-unused.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-pmic-keys.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-pmic-wrap.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-scpsys-bringup.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-scpsys-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-scpsys.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-smi-dbg.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-smi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-socinfo.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-spmi-pmic-adc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-spmi-pmic.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-swpm-perf-arm-pmu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-uart-apdma.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk-vmm-spm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_battery_oc_throttling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_charger_algorithm_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_charger_framework.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_chg_type_det.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_dcm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_disp_notify.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_dramc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_dynamic_loading_throttling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_iommu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_low_battery_throttling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_mdpm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_panel_ext.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pbm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pd_adapter.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pd_charging.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pep.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pep20.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pep40.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pep45.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_pep50.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_printk_ctrl.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_rpmsg_mbox.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_slbc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_sync.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_tinysys_ipi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtk_wdt.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mtu3.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/mux_switch.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/nt36532.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/nu2115_chargepump.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/nvmem_mtk-devinfo.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-alpha-jdi-nt36672e-cphy-vdo.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-alpha-jdi-nt36672e-vdo-120hz-hfp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-alpha-jdi-nt36672e-vdo-120hz.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-alpha-jdi-nt36672e-vdo-60hz.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-nt36532-dsi-vdo-boe.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-nt36532-dsi-vdo-tianma-paper.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-nt36532-dsi-vdo-tianma.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-nt37801-cmd-fhd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-samsung-ana6705-cmd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-truly-nt35595-cmd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/panel-truly-td4330-cmd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pd-chk-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pd_dbg_info.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/phy-mtk-ufs.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/phy-mtk-xsphy.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pidmap.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pinctrl-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pinctrl-mtk-common-v2_debug.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pinctrl-mtk-v2.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pmic_lbat_service.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pmic_lvsys_notify.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/ps5170.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/pwm-mtk-disp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/reboot-mode.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/regulator-vibrator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/reset-ti-syscon.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rpmb-mtk.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rpmb.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rt4831a_drv.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rt5133-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rt6160-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rt_pd_manager.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/rtc-mt6685.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sec-rng.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sec.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sensors_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sgm37604a.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sgm37604a_second.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/slbc_ipi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/slbc_mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/slbc_trace.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/sm5109.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/smpu-hook-v1.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/smpu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/spi-mt65xx.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/spmi-mtk-mpu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/spmi-mtk-pmif.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/syscon-reboot-mode.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/system_heap.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/tcpc_class.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/tcpc_mt6375.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/tcpci_late_sync.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/teeperf.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/timer-mediatek.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/tinysys-scmi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/tui-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/uarthub_drv.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/ufs-mediatek-dbg.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/ufs-mediatek-mod.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/upm6720_chargepump.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/usb_boost.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/usb_dp_selector.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/usb_meta.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/vcp_status.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_ramdisk/xhci-mtk-hcd-v2.ko \

# vendor_dlkm modules (alphabetical)
BOARD_VENDOR_KERNEL_MODULES := \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/adsp-v2.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/apu_top.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/apusys.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/atf_logger.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/audio_ipi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/backlight_cooling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/board_temp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/bt_drv_6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/camera_af_media.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/camera_dpe_isp7sp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/camera_eeprom_v4l2.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/ccd_rpmsg.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/cfg80211.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/charger_cooling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/clk-dbg-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/clk-disable-unused.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/cmdq-sec-drv.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/cmdq-test.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/connadp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/connfem.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/conninfra.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/connscp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/cpudvfs.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/cpufreq_sugov_ext.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/cpuqos_v3.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/extend_reclaim.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/fhctl.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/flashlight.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/flashlights-ocp811.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/fmradio_drv_connac2x.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/fpsgo.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/frs.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/ged.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gf_tee.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gps_drv_dl_v051.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gps_pwr.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gps_scp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gpueb.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gt9772b.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gz_ipc_mod.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gz_irq_mod.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gz_log_mod.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gz_main_mod.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gz_trusty_mod.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gz_tz_system.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/gz_virtio_mod.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/hbt.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/hf_manager.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/imgsensor-glue.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/imgsensor.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/iommu_test.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/jpeg-driver.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/lan78xx.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/lm3643.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/load_track.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mac80211.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/main2_vcm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/main3_vcm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/main_vcm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mali_dmabuf_test_mt6897_r44.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mali_kbase_mt6897_r44.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mali_mgm_mt6897_r44.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mali_prot_alloc_mt6897_r44.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mcupm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/met.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/met_backlight_api.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/met_emi_api.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/met_gpu_adv_api.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/met_gpu_api.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/met_gpueb_api.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/met_ipi_api.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/met_mcupm_api.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/met_scmi_api.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/met_sspm_api.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/met_vcore_api.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mii.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/msync2_frd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mt6368-accdet.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mt6897-mt6368.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-btcvsd.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-cam-isp7sp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-composite.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-dvfsrc-start.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-ipesys-me.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-lpm-dbg-common-v2.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-lpm-dbg-mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-lpm-plat-v1.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-lpm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-mbox.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-mmdvfs-v3-start.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-pm-domain-disable-unused.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-pmic-oc-debug.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-pwm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-scp-audiocommon.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-scp-ultra.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-scp-vow.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-soc-offload-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-sp-spk-amp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-ssc-dbg-v2.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-ssc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-swpm-audio-dbg-v6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-swpm-core-dbg-v6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-swpm-cpu-dbg-v6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-swpm-dbg-common-v1.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-swpm-dbg-v6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-swpm-mem-dbg-v6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-swpm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-vcodec-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-vcodec-dec-v2.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-vcodec-enc-v2.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-vcu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-vmm-isp71-regulator.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-vmm-notifier.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk-vow.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_aie.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_aie_debug_7sp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_battery_oc_throttling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_bp_thl.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_ccd_remoteproc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_ccu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_cm_ipi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_cm_mgr.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_cm_mgr_mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_core_ctl.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_cpu_power_throttling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_disp_sec.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_dynamic_loading_throttling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_et.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_fpsgo.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_gpu_hal.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_gpu_power_throttling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_gpu_qos.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_gpufreq_mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_gpufreq_wrapper.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_hcp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_heap_debug.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_imgsys_cmdq.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_imgsys_isp7sp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_imgsys_v4l2.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_ioctl_powerhal.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_ioctl_touch_boost.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_irtx_pwm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_jpeg.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_low_battery_throttling.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_mbraink.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_mdpm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_pbm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_peak_power_budget.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_perf_common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_perf_ioctl.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_perf_ioctl_magt.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_qos.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_rpmsg_mbox.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_sec_heap.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_tinysys_ipi.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_u_ether.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/mtk_usb_f_rndis.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/nt36532.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/nvmem-mt635x-efuse.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/pda_drv_mt6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/pmic_temp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/pmic_tia.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/powerhal_cpu_ctrl.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/reboot-mode.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/richtek_spm_cls.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/rps_perf.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/sapu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/scheduler.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/scheduler_ext.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/scp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/sec.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/sensorhub.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/smsc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/smsc75xx.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/smsc95xx.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/snd-soc-audiodsp-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/snd-soc-aw883xx.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/snd-soc-mt6368.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/snd-soc-mt6897-afe.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/snd-soc-mtk-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/snd-soc-mtk-scp-ultra.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/snd-soc-rt5512.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/snd-soc-tfa98xx.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/soc_temp_lvts.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/spmi-mtk-mpu.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/sspm_v3.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/sub_vcm.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/syscon-reboot-mode.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/t-base-tui.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/task_turbo.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/thermal-generic-adc.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/thermal_interface.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/thermal_trace.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/tmem_ffa.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/touch_boost.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/trace_mmstat.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/tui-common.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/uload_ind.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/usbnet.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/vcp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/vtskin_temp.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/widevine_driver.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/wlan_drv_gen4m_6897.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/wmt_chrdev_wifi_connac2.ko \
    $(DEVICE_PATH)/prebuilts/modules/vendor_dlkm/zram_ext.ko \

# system_dlkm modules (alphabetical)
BOARD_SYSTEM_KERNEL_MODULES := \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/6lowpan.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/8021q.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/aqc111.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/asix.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/ax88179_178a.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/bluetooth.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/bsd_comp.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/btbcm.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/btqca.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/btsdio.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/can-bcm.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/can-dev.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/can-gw.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/can-raw.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/can.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/cdc-acm.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/cdc_eem.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/cdc_ether.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/cdc_ncm.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/diag.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/ftdi_sio.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/gzvm.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/hci_uart.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/hidp.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/ieee802154.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/ieee802154_6lowpan.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/ieee802154_socket.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/kheaders.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/l2tp_core.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/l2tp_ppp.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/libarc4.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/mac802154.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/mii.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/nfc.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/nhc_dest.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/nhc_fragment.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/nhc_hop.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/nhc_ipv6.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/nhc_mobility.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/nhc_routing.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/nhc_udp.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/ppp_deflate.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/ppp_generic.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/ppp_mppe.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/pppox.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/pptp.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/r8152.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/r8153_ecm.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/rfcomm.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/rfkill.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/rtl8150.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/slcan.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/slhc.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/tipc.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/usbnet.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/usbserial.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/vcan.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/wwan.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/zram.ko \
    $(DEVICE_PATH)/prebuilts/modules/system_dlkm/zsmalloc.ko \

# vendor_ramdisk load order (from stock vendor_boot)
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := \
    bootprof.ko \
    mrdump.ko \
    aee_aed.ko \
    aee_hangdet.ko \
    monitor_hang.ko \
    mkp.ko \
    dbgtop-drm.ko \
    irq-dbg.ko \
    cache-parity.ko \
    mtk_sync.ko \
    mtk_disp_notify.ko \
    mtk_printk_ctrl.ko \
    log_store.ko \
    nvmem_mtk-devinfo.ko \
    mtk_wdt.ko \
    timer-mediatek.ko \
    sec-rng.ko \
    device-apc-common.ko \
    device-apc-mt6897.ko \
    pinctrl-mtk-v2.ko \
    pinctrl-mt6897.ko \
    clk-common.ko \
    clk-mt6897.ko \
    clk-mt6897-adsp.ko \
    clk-mt6897-cam.ko \
    clk-mt6897-img.ko \
    clk-mt6897-mmsys.ko \
    clk-mt6897-peri.ko \
    clk-mt6897-bus.ko \
    clk-mt6897-mdpsys.ko \
    clk-mt6897-vlp.ko \
    clk-mt6897-vcodec.ko \
    clk-mt6897-ccu.ko \
    mtk-pmic-wrap.ko \
    mtk-spmi-pmic.ko \
    spmi-mtk-pmif.ko \
    mt6315-regulator.ko \
    mt6363-regulator.ko \
    mt6368-regulator.ko \
    mtk-vmm-spm.ko \
    mtk-scpsys.ko \
    mtk-scpsys-mt6897.ko \
    mtk-scpsys-bringup.ko \
    mt6897_dcm.ko \
    mtk_dcm.ko \
    mtk-dvfsrc.ko \
    mtk-dvfsrc-regulator.ko \
    mtk-dvfsrc-devfreq.ko \
    clk-bringup.ko \
    clk-chk-mt6897.ko \
    pd-chk-mt6897.ko \
    clk-fmeter-mt6897.ko \
    mtk-emi.ko \
    mtk-dvfsrc-helper.ko \
    mtk_dramc.ko \
    mtk-smi.ko \
    mtk-smi-dbg.ko \
    mtk-icc-core.ko \
    mtk-mmdvfs-ftrace.ko \
    mtk-mmdvfs-v3.ko \
    mtk-mmdvfs.ko \
    mtk-mmdvfs-debug.ko \
    mmqos-common.ko \
    mmqos-mt6897.ko \
    iommu_debug.ko \
    iommu_secure.ko \
    mtk_iommu.ko \
    system_heap.ko \
    mtk-mminfra-debug.ko \
    mtk-mminfra-imax.ko \
    mtk-cmdq-drv-ext.ko \
    cmdq-platform-mt6897.ko \
    cmdq_helper_inf.ko \
    mdp_drv_mt6897.ko \
    mtk-mml.ko \
    mtk-mml-mt6897.ko \
    drm_dma_helper.ko \
    mtk_panel_ext.ko \
    panel-alpha-jdi-nt36672e-vdo-60hz.ko \
    panel-nt36532-dsi-vdo-boe.ko \
    panel-nt36532-dsi-vdo-tianma.ko \
    panel-nt36532-dsi-vdo-tianma-paper.ko \
    panel-alpha-jdi-nt36672e-vdo-120hz.ko \
    panel-alpha-jdi-nt36672e-cphy-vdo.ko \
    panel-alpha-jdi-nt36672e-vdo-120hz-hfp.ko \
    panel-truly-td4330-cmd.ko \
    panel-truly-nt35595-cmd.ko \
    panel-nt37801-cmd-fhd.ko \
    panel-samsung-ana6705-cmd.ko \
    mtk-afe-external.ko \
    mediatek-drm-gateic.ko \
    mediatek-drm-panel-drv.ko \
    drm_display_helper.ko \
    mediatek-drm.ko \
    aee_rs.ko \
    rt4831a_drv.ko \
    sm5109.ko \
    sgm37604a.ko \
    sgm37604a_second.ko \
    mmprofile.ko \
    mtk-uart-apdma.ko \
    uarthub_drv.ko \
    8250_mtk.ko \
    phy-mtk-xsphy.ko \
    xhci-mtk-hcd-v2.ko \
    mtu3.ko \
    usb_boost.ko \
    mux_switch.ko \
    ps5170.ko \
    usb_dp_selector.ko \
    mt6685-core.ko \
    mt6685-audclk.ko \
    mt6338-core.ko \
    clkbuf.ko \
    ffa-module.ko \
    teeperf.ko \
    mcDrvModule-ffa.ko \
    isee-ffa.ko \
    mtk-spmi-pmic-adc.ko \
    pinctrl-mtk-common-v2_debug.ko \
    cqhci.ko \
    mtk-mmc-dbg.ko \
    mtk-mmc.ko \
    phy-mtk-ufs.ko \
    rpmb.ko \
    rpmb-mtk.ko \
    ufs-mediatek-mod.ko \
    ufs-mediatek-dbg.ko \
    blocktag.ko \
    pidmap.ko \
    mtk-pmic-keys.ko \
    mtk-kpd.ko \
    tui-common.ko \
    regulator-vibrator.ko \
    i2c-mt65xx.ko \
    mtk_dramc.ko \
    spi-mt65xx.ko \
    mt6375.ko \
    nt36532.ko \
    extdev_io_class.ko \
    rt5133-regulator.ko \
    rt6160-regulator.ko \
    rtc-mt6685.ko \
    industrialio-triggered-buffer.ko \
    kfifo_buf.ko \
    mt6375-adc.ko \
    mt6375-auxadc.ko \
    adapter_class.ko \
    charger_class.ko \
    mtk_charger_algorithm_class.ko \
    mt6375-charger.ko \
    pd_dbg_info.ko \
    tcpc_class.ko \
    tcpc_mt6375.ko \
    mtk_pd_adapter.ko \
    mt6375-battery.ko \
    mtk_charger_framework.ko \
    mtk_chg_type_det.ko \
    mtk_pep40.ko \
    mtk_pep45.ko \
    mtk_pep50.ko \
    mtk_pd_charging.ko \
    mtk_pep20.ko \
    mtk_pep.ko \
    rt_pd_manager.ko \
    fsa4480-i2c.ko \
    pwm-mtk-disp.ko \
    leds-mtk.ko \
    leds-mtk-disp.ko \
    leds-mtk-pwm.ko \
    extcon-mtk-usb.ko \
    tcpci_late_sync.ko \
    mtk-mbox-mailbox.ko \
    tinysys-scmi.ko \
    arm_dsu_pmu.ko \
    mtk-swpm-perf-arm-pmu.ko \
    pmic_lbat_service.ko \
    pmic_lvsys_notify.ko \
    reset-ti-syscon.ko \
    reboot-mode.ko \
    syscon-reboot-mode.ko \
    adsp.ko \
    mtk_slbc.ko \
    slbc_mt6897.ko \
    slbc_ipi.ko \
    slbc_trace.ko \
    mediatek-cpufreq-hw.ko \
    vcp_status.ko \
    emi.ko \
    emi-mpu.ko \
    smpu.ko \
    smpu-hook-v1.ko \
    emi-slb.ko \
    mtk-socinfo.ko \
    mm8013a_gauge.ko \
    upm6720_chargepump.ko \
    nu2115_chargepump.ko \
    lenovo_charge_sysfs.ko \
    hx9031as.ko \
    hx9036.ko \
    sensors_class.ko \
    hall.ko \
    usb_meta.ko \
    dbg_error_flag.ko \
    bus-parity.ko \
    last_bus.ko \
    hardware_info.ko \

# vendor_dlkm load order (from stock vendor_dlkm modules.load)
BOARD_VENDOR_KERNEL_MODULES_LOAD := \
    cfg80211.ko \
    mac80211.ko \
    reboot-mode.ko \
    syscon-reboot-mode.ko \
    spmi-mtk-mpu.ko \
    fhctl.ko \
    clk-dbg-mt6897.ko \
    mtk-vmm-notifier.ko \
    cmdq-sec-drv.ko \
    mtk_et.ko \
    mtk_hcp.ko \
    mtk-ipesys-me.ko \
    mtk_imgsys_cmdq.ko \
    mtk_imgsys_v4l2.ko \
    mtk_imgsys_isp7sp.ko \
    mtk_aie.ko \
    mtk_aie_debug_7sp.ko \
    camera_dpe_isp7sp.ko \
    mtk-pmic-oc-debug.ko \
    mtk-ssc.ko \
    mtk-ssc-dbg-v2.ko \
    trace_mmstat.ko \
    rps_perf.ko \
    mtk-pwm.ko \
    mtk_irtx_pwm.ko \
    sspm_v3.ko \
    mtk_battery_oc_throttling.ko \
    mtk_low_battery_throttling.ko \
    mtk_dynamic_loading_throttling.ko \
    mtk_bp_thl.ko \
    mtk_cpu_power_throttling.ko \
    mtk_peak_power_budget.ko \
    mtk_pbm.ko \
    mtk_mdpm.ko \
    gpueb.ko \
    mtk_gpu_hal.ko \
    mtk_gpu_power_throttling.ko \
    mtk_gpufreq_wrapper.ko \
    mtk_gpufreq_mt6897.ko \
    ged.ko \
    gf_tee.ko \
    mali_prot_alloc_mt6897_r44.ko \
    mali_mgm_mt6897_r44.ko \
    mali_kbase_mt6897_r44.ko \
    mali_dmabuf_test_mt6897_r44.ko \
    nvmem-mt635x-efuse.ko \
    adsp-v2.ko \
    audio_ipi.ko \
    mtk-scp-audiocommon.ko \
    snd-soc-rt5512.ko \
    richtek_spm_cls.ko \
    snd-soc-tfa98xx.ko \
    snd-soc-aw883xx.ko \
    mtk-sp-spk-amp.ko \
    mtk-btcvsd.ko \
    snd-soc-mtk-common.ko \
    snd-soc-mt6897-afe.ko \
    snd-soc-mt6368.ko \
    snd-soc-audiodsp-common.ko \
    mtk-scp-ultra.ko \
    snd-soc-mtk-scp-ultra.ko \
    mtk-soc-offload-common.ko \
    mt6897-mt6368.ko \
    soc_temp_lvts.ko \
    pmic_temp.ko \
    thermal-generic-adc.ko \
    thermal_trace.ko \
    board_temp.ko \
    vtskin_temp.ko \
    charger_cooling.ko \
    backlight_cooling.ko \
    thermal_interface.ko \
    mtk_gpu_qos.ko \
    mt6368-accdet.ko \
    cpudvfs.ko \
    vcp.ko \
    mtk-vcu.ko \
    mtk_jpeg.ko \
    mtk-vcodec-common.ko \
    mtk-vcodec-dec-v2.ko \
    mtk-vcodec-enc-v2.ko \
    jpeg-driver.ko \
    powerhal_cpu_ctrl.ko \
    cpufreq_sugov_ext.ko \
    scheduler.ko \
    cpuqos_v3.ko \
    mtk_ccu.ko \
    mtk-vmm-isp71-regulator.ko \
    mtk_rpmsg_mbox.ko \
    mtk-mbox.ko \
    mtk_tinysys_ipi.ko \
    scp.ko \
    mtk-vow.ko \
    mtk-scp-vow.ko \
    mcupm.ko \
    mtk_ccd_remoteproc.ko \
    ccd_rpmsg.ko \
    mtk_cm_ipi.ko \
    mtk_cm_mgr.ko \
    mtk_cm_mgr_mt6897.ko \
    mtk-cam-isp7sp.ko \
    imgsensor-glue.ko \
    imgsensor.ko \
    camera_eeprom_v4l2.ko \
    mtk_fpsgo.ko \
    mtk_perf_ioctl.ko \
    fpsgo.ko \
    frs.ko \
    mtk_perf_ioctl_magt.ko \
    mtk-swpm.ko \
    mtk-swpm-dbg-common-v1.ko \
    mtk-swpm-dbg-v6897.ko \
    mtk-swpm-mem-dbg-v6897.ko \
    mtk-swpm-core-dbg-v6897.ko \
    mtk-swpm-cpu-dbg-v6897.ko \
    mtk-swpm-audio-dbg-v6897.ko \
    connadp.ko \
    connscp.ko \
    connfem.ko \
    conninfra.ko \
    wmt_chrdev_wifi_connac2.ko \
    wlan_drv_gen4m_6897.ko \
    mtk-lpm.ko \
    mtk-lpm-dbg-common-v2.ko \
    mtk-lpm-plat-v1.ko \
    mtk-lpm-dbg-mt6897.ko \
    fmradio_drv_connac2x.ko \
    mtk_qos.ko \
    touch_boost.ko \
    mtk_ioctl_touch_boost.ko \
    mtk_ioctl_powerhal.ko \
    hf_manager.ko \
    sensorhub.ko \
    mtk-composite.ko \
    lm3643.ko \
    flashlights-ocp811.ko \
    flashlight.ko \
    gz_trusty_mod.ko \
    gz_ipc_mod.ko \
    gz_irq_mod.ko \
    gz_virtio_mod.ko \
    gz_tz_system.ko \
    gz_main_mod.ko \
    gz_log_mod.ko \
    tmem_ffa.ko \
    mtk_sec_heap.ko \
    mtk_heap_debug.ko \
    sapu.ko \
    iommu_test.ko \
    t-base-tui.ko \
    camera_af_media.ko \
    main_vcm.ko \
    main2_vcm.ko \
    main3_vcm.ko \
    sub_vcm.ko \
    gt9772b.ko \
    pda_drv_mt6897.ko \
    atf_logger.ko \
    mtk_core_ctl.ko \
    mtk-dvfsrc-start.ko \
    bt_drv_6897.ko \
    mtk_u_ether.ko \
    mtk_usb_f_rndis.ko \
    clk-disable-unused.ko \
    mtk-pm-domain-disable-unused.ko \
    hbt.ko \
    apu_top.ko \
    apusys.ko \
    widevine_driver.ko \
    task_turbo.ko \
    mtk_perf_common.ko \
    mtk_disp_sec.ko \
    sec.ko \
    mtk-mmdvfs-v3-start.ko \
    uload_ind.ko \
    load_track.ko \
    mtk_mbraink.ko \
    mii.ko \
    usbnet.ko \
    lan78xx.ko \
    smsc.ko \
    smsc75xx.ko \
    smsc95xx.ko \
    zram_ext.ko \
    extend_reclaim.ko \
    pmic_tia.ko \

# system_dlkm load order (from stock system_dlkm modules.load)
BOARD_SYSTEM_KERNEL_MODULES_LOAD := \
    gzvm.ko \
    kheaders.ko \
    zsmalloc.ko \
    libarc4.ko \
    zram.ko \
    mii.ko \
    can-dev.ko \
    vcan.ko \
    slcan.ko \
    ppp_generic.ko \
    bsd_comp.ko \
    ppp_deflate.ko \
    ppp_mppe.ko \
    pppox.ko \
    pptp.ko \
    slhc.ko \
    wwan.ko \
    rtl8150.ko \
    r8152.ko \
    asix.ko \
    ax88179_178a.ko \
    cdc_ether.ko \
    cdc_eem.ko \
    usbnet.ko \
    cdc_ncm.ko \
    aqc111.ko \
    r8153_ecm.ko \
    cdc-acm.ko \
    usbserial.ko \
    ftdi_sio.ko \
    hci_uart.ko \
    btsdio.ko \
    btbcm.ko \
    btqca.ko \
    8021q.ko \
    can.ko \
    can-raw.ko \
    can-bcm.ko \
    can-gw.ko \
    bluetooth.ko \
    rfcomm.ko \
    hidp.ko \
    l2tp_core.ko \
    l2tp_ppp.ko \
    tipc.ko \
    diag.ko \
    rfkill.ko \
    6lowpan.ko \
    nhc_dest.ko \
    nhc_fragment.ko \
    nhc_hop.ko \
    nhc_ipv6.ko \
    nhc_mobility.ko \
    nhc_routing.ko \
    nhc_udp.ko \
    ieee802154_6lowpan.ko \
    ieee802154.ko \
    ieee802154_socket.ko \
    mac802154.ko \
    nfc.ko \
